version: '3'

services:
  factorio:
    image: factoriotools/factorio:2.0.20
    container_name: factorio-space-age
    restart: unless-stopped
    ports:
      - "27015:27015/tcp"
      - "34197:34197/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/factorio
    environment:
      - TZ=Asia/Shanghai
