FROM chromedp/headless-shell:latest

RUN apt-get update -y \
    && apt-get install -y fonts-noto \
    && apt-get install -y fonts-noto-cjk \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/

EXPOSE 9222
ENV LANG en-US.UTF-8
ENV PATH /headless-shell:$PATH
ENTRYPOINT [ "/headless-shell/headless-shell", "--no-sandbox", "--use-gl=angle", "--use-angle=swiftshader", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222" ]
